# Generated by Django 3.0.6 on 2020-06-04 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2020, 6, 4, 17, 58, 47, 564939))),
                ('done', models.CharField(default='No', max_length=32)),
            ],
        ),
    ]
